name: Build Custom Telegram iOS 26

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 1

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Build Dependencies
        run: |
          brew install yasm
          brew install bazelisk

      - name: Compile Telegram
        env:
          API_ID: "6"
          API_HASH: "eb06d4abfb49dc3eeb1aeb98ae0f581e"
        run: |
          # Передаем скрипту все требуемые параметры, чтобы он отстал
          python3 build-system/Make/Make.py \
            --cacheDir="$HOME/bazel-cache" \
            build \
            --configurationPath=build-system/template_minimal_development_configuration.json \
            --buildNumber 100000 \
            --xcodeManagedCodesigning \
            --configuration=release_arm64

      - name: Package to IPA
        run: |
          echo "Упаковка скомпилированного .app в .ipa..."
          mkdir -p Payload
          find . -type d -name "Telegram.app" -exec cp -R {} Payload/ \;
          zip -qr Telegram-Custom.ipa Payload

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Telegram-Custom-Build
          path: Telegram-Custom.ipa
          retention-days: 7
